### ISSUE TITLE
Tutorial Revamp

### ISSUE THREAD

**Issue by harshpavuluri** [ironhacks/Tutorials-COVID-19#16]
Summary:
This issue is dedicated to making changes to the current tutorials to make them more in-depth and making new tutorials for the the upcoming Fall 2022 hack.

Tasks:
- [x] Revamp old tutorials for readability and in-depth
- [x] Bring in new tutorial (Lag regression)

*Sub tasks posted in comments below

**Comment by harshpavuluri** [comment]
Structuring the tutorials:

For the revamp, I wanted to do a top down change to make sure that the content is easily readable for students. @rsundhar2002 @sbrunswi, this will be the bulk of what I ask just for ideas and brainstorming here. After we determine a good general structure to follow, I should be able to build those tutorials and then ask for feedback on those things.

**Comment by rsundhar2002** [comment]
After looking at the Tutorials I think the ones that we should start revamping are  2,4 and 5. Starting with Tutorial 2 I think that there is not enough visual examples. By visual examples I do not just mean images and instructions I think it would be a big help if we added more video's. By adding more video's I think it will be more engaging for the user in terms of learning. In Tutorial 4 one thing I see is there is a lot of explaining about the visuals. The main purpose of adding visuals is to make it simpler for the people learning to understand the material. By adding more text it makes it more confusing so try simplifying the text so to make it easier to understand. In Tutorial 5 the Image seemed to be confusing I would recommend adding a tutorial that trains them how to read and properly use a map. I also think to emphasize more about how to write packages and summaries. I am still in the process of reviewing Tutorial number 6. I will let you know if I have any other feedback.

**Comment by rsundhar2002** [comment]
Hi Harsha,
I made some comments regarding the tutorials on Github after reviewing a
few of them. I am still in the process of reviewing them and will continue
to add more feedback or anything else that comes to mind.

Regards

Rahul

**Comment by harshpavuluri** [comment]
Thats some great feedback! Thank you! I'll try to work that into the newer tutorials! Tutorial 5 I might archive because its not super relevant to the upcoming hack.

**Comment by harshpavuluri** [comment]
Notes from 8/27 meeting

Tutorial 1: how to use a notebook (Existing and improve)
Tutorial 2: Stays the same (Improve)
Tutorial 3: Stays the same (Improve and expand)
Tutorial 4: Lag Regression (At the end)
Tutorial 5: ??? (How to write summary)

- Build from the examples that we currently have (Just have to write a markdown) (For later thought)
- Improve the markdown for each of the tutorials
- Video records when each one once each one completed
- Work on tutorial 1 with code/image embeddings

https://medium.com/analytics-vidhya/from-basic-to-intermediate-sql-in-10-minutes-42b960ed6f9e

https://medium.com/edureka/sql-interview-questions-162f97f37ac2

https://medium.com/@mygreatlearning/step-by-step-regression-analysis-f7e3e3ebf296

**Comment by harshpavuluri** [comment]
Tutorial 1 draft has been merged into master now. I've begun creating the new tutorial 2

**Comment by jialincheoh** [comment]
@harshpavuluri  , @rsundhar2002 , @sbrunswi , would something like this be useful for recording the tutorials? https://www.showme.com/

**Comment by harshpavuluri** [comment]
> @harshpavuluri , @rsundhar2002 , @sbrunswi , would something like this be useful for recording the tutorials? https://www.showme.com/

Ya I can definetly take a look at that in the future. I currently haven't even thought about recording videos yet until I have finished the drafts for the new tutorials. But I will keep it in the back of my mind. I can record the tutorials really well with OBS currently and get great quality out of it on my main PC in terms of video and audio. Youtube should be able to handle the file sizes.

**Comment by harshpavuluri** [comment]
@sbrunswi The 2 PRs are ready for review. Once confirmed as an initial draft before showing to partners, I'll merge them in. Try to use the review section since I can go to those locations directly and fix those problems

**Comment by harshpavuluri** [comment]
@rsundhar2002 Going to ask for another review here if you aren't too busy. I have some of the new tutorials in the main branch and then others are in other branches I haven't merged yet. 

Just in case, to switch branches in github, Go to the tutorials repository and right above where you see the files in the top right (above my username), you'll see a drop down menu with branches. You can just click those and switch between those. 

LMK you feedback! You can detail them in the according PRs and this issue as well (whichever is easiest for you). Everything is in this milestone.

https://github.com/ironhacks/Tutorials-COVID-19/milestone/2
