### ISSUE TITLE
Create tutorial #4: How to prepare a valid submission

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/Tutorials-COVID-19#2]
**create an additional tutorial 4**

A rough outline of tutorial 4 (markdown) is presented here. 

The issue about the timestamp we discussed here:  https://github.com/ironhacks/Tutorials-COVID-19/blob/master/tutorials-fall-2020/%23%23%20Tutorial_4-notes.md

https://github.com/ironhacks/COVID-19-August-2020-research/issues/33

@charrismatic  can you do the Python one? I do the R. 

Thank you!

**Comment by charrismatic** [comment]
Resolved https://github.com/ironhacks/Tutorials-COVID-19/blob/master/tutorials-fall-2020/python/tutorial-4-submissions.md
