### ISSUE TITLE
[Review] Tutorial 2 MD and Notebook Changes

### ISSUE THREAD

**Issue by harshpavuluri** [ironhacks/Tutorials-COVID-19#22]
This issue is dedicated to the changes needed on tutorial 2 to reflect the new authentication for the student.

Tasks

- [x] Add content about terminal commands to the markdown and images
- [x] Fix notebook to reflect a working notebook after usage with those terminal commands
- [x] Change beginning description to make sure that people have to run the terminal commands before running the notebook

**Comment by sbrunswi** [comment]
@jialincheoh  is reviewing this tutorial right now so I keep this as pending/review but jia will close the issue.

**Comment by jialincheoh** [comment]
This issue is resolved @sbrunswi , so I am going to close it
