### ISSUE TITLE
Submission template

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/Tutorials-COVID-19#25]
**Problem**
the submission template does not contain the info about the authentication; it also has too much info that would make the people submit notebooks with a lot of code. 

**Solution**
We need the following: 
1) A template that has a block on authentication
2) We need to remove the "background section"
3) We also need to review the tutorial related how to prepare a submission afterwards!

**Comment by jialincheoh** [comment]
> **Problem** the submission template does not contain the info about the authentication; it also has too much info that would make the people submit notebooks with a lot of code.
> 
> **Solution** We need the following:
> 
> 1. A template that has a block on authentication
> 2. We need to remove the "background section"
> 3. We also need to review the tutorial related how to prepare a submission afterwards!

Background section removed from template @sbrunswi

**Comment by sbrunswi** [comment]
@jialincheoh : please change the link to the submission link in 

- [x] task
- [x] tutorial 6a
- [x] overview page
- [x] Submission template

**Comment by sbrunswi** [comment]
@jialincheoh  - please confirm that this is sorted!

**Comment by jialincheoh** [comment]
@sbrunswi this is solved.
