### ISSUE TITLE
[Management] Tutorial Live Sessions and Preparation

### ISSUE THREAD

**Issue by harshpavuluri** [ironhacks/Tutorials-COVID-19#26]
Summary:

This issue is related to the live sessions that will be hosted (Check the calendar for dates and times). This should include outlines for the sessions, recordings, etc.

Tasks:
- [x] Create outlines for all 6 tutorials to prepare for the live session
- [x] Confirm recording method 
- [x] Make sure that we can upload videos to Youtube so participants may reference them later

**Comment by harshpavuluri** [comment]
For recording, I can use OBS for recording since I have that setup on my main desktop. I should be able to record 1080p 60 FPS, so everything should look clear in terms of the recording

**Comment by harshpavuluri** [comment]
@sbrunswi 

https://docs.google.com/presentation/d/1zf9J0mn5IW3788ljLCX3coyvnUHQWjAyWnL5oC2Arxc/edit#slide=id.g17aa8e3e4fd_0_1

First presentation for tomorrow. Essentially introduction to Ironhacks and then modified the end to include the task as well as the tutorial walk through. Added in notes on the slide the outline draft for that Tutorial walkthrough

**Comment by harshpavuluri** [comment]
https://docs.google.com/document/d/1oNJgLIqQ60zUYeb-Qtj2xez4R1bmVOR3DdaGOMSf00Y/edit

Tutorials Script is above (same location as the presentation for 11/1)

@jialincheoh if you can give those both a review, that would help out a ton

**Comment by jialincheoh** [comment]
thanks @harshpavuluri , will take a look now

**Comment by harshpavuluri** [comment]
Uploaded the first draft video to drive



https://drive.google.com/file/d/1PooCfGYhb_mocShjHJ9PtHBLyZZDmDbU/view?usp=share_link



A bit of a rough recording since its my first take, but let me know if I have to adjust anything volume wise or screen wise. Also points on the script would be great



https://drive.google.com/drive/u/0/folders/11hq_nqCVu_AeqGT7bW5b-Pf3uMTPDC8P

Everything for live sessions and recordings can be found above

**Comment by aronlindberg** [comment]
@sbrunswi: I have reviewed the slides and cleaned them up a little bit.

**Comment by sbrunswi** [comment]
@aronlindberg  - I need a screenshot from a user who is not registered to all hacks like I am. Please take a screenshot of the overview page and post it here. I need it by 6 pm! @crystalhappycat  you could do the same!

**Comment by crystalhappycat** [comment]
All my three emails are registered. Does that still work for me?

**Comment by aronlindberg** [comment]
<img width="1511" alt="Screen Shot 2022-11-01 at 4 23 14 PM" src="https://user-images.githubusercontent.com/1494523/199333617-8f854fe2-7c43-43dd-a0d1-54b4c9aad7b5.png">

**Comment by sbrunswi** [comment]
I was thinking of the overview of all hacks

**Comment by sbrunswi** [comment]
@aronlindberg  and @crystalhappycat : here are the final slides published to the web: https://docs.google.com/presentation/d/e/2PACX-1vSC3-Ub-bIQd8MM2gsSjG00sqBcAorrj4SoiDRxlrVtaI46rRMkFJhw25luLBJz-dZkmGS9gpEFhWAI/pub?start=false&loop=false&delayms=3000

We will share them via the website! Please include those in the forum post!

**Comment by aronlindberg** [comment]
<img width="1491" alt="Screen Shot 2022-11-01 at 6 39 28 PM" src="https://user-images.githubusercontent.com/1494523/199355361-53c1af49-f0aa-48a2-8e24-6f1abcc94b26.png">

**Comment by harshpavuluri** [comment]
Since live sessions have concluded, closing
