### ISSUE TITLE
[Tutorial] Amend Tutorial 6b 

### ISSUE THREAD

**Issue by jialincheoh** [ironhacks/Tutorials-COVID-19#27]
- Amend Tutorial 6b to look like tutorials. 

- Just keep one example on ARIMA

- Screenshot on where to place the summary

- Criteria that should go into the summary

**Comment by harshpavuluri** [comment]
I think in terms of structure, it looks ok. Might need to flavor and break it up with some images from the submission page. This will help spread the content out a bit so that its not a big blob of text. At least should help with retention

**Comment by jialincheoh** [comment]
This is completed - Link to tutorial 6b -  https://dev.ironhacks.com/hacks/fall-22-dev-hack/tutorials/LtjgTOPogWALncdw07oE       @sbrunswi  @harshpavuluri 

Question, are we specifying 500 characters minimum or 250 words minimum? I think this needs to be consistent everywhere. 

Platform stated 500 characters minimum -> 

<img width="1202" alt="Screenshot 2022-11-01 at 5 46 18 PM" src="https://user-images.githubusercontent.com/19192631/199209400-2a94bf66-1767-4adc-996a-48cec5b44d8e.png">

**Comment by sbrunswi** [comment]
We have to say 500 now. Should I fix it or you?

**Comment by sbrunswi** [comment]
@crystalhappycat: Could you please suggest a bullet list for the `description of the algorithm`. Can you add it here?

**Comment by crystalhappycat** [comment]
Description of the algorithm
* Fundamental logic of the algorithm. Please describe how the algorithm actually works, including statistical reasoning, optimization procedure, etc.
* Appropriate conditions for the algorithm. Please describe the conditions (i.e., problem type, data structure) where the algorithm will perform effectively and ineffectively.
* Essential parameters to be tuned. Please describe what the essential parameters for this algorithm mean and how they are tuned to get an optimal model. 


@sbrunswi @jialincheoh

**Comment by sbrunswi** [comment]
@jialincheoh  - can you finish this accordingly?
