### ISSUE TITLE
[Tutorial] Update Tutorials 1 and 2 to reflect issues on Tutorials 1 & 2 on Zoom 

### ISSUE THREAD

**Issue by jialincheoh** [ironhacks/Tutorials-COVID-19#28]
Update Tutorials 1 and 2 to reflect issues on Tutorials 1 & 2 on Zoom 

- [x] re-check authentication issue 
- [x] update tutorials to mention re-open notebook after !pip install db-dtypes
- [x] Update video recording on tutorials 1 and 2
- [x] Update markdown on tutorials 1 and 2

**Comment by harshpavuluri** [comment]
Tutorial 2 has now been updated with the fixed authentication. The notebook has been updated as well with these fixes. I've also included the "db-dtypes" fix in the MD and notebook as well (made this a runnable cell for ease)

Unsure what needs to be changed on T1, I don't think we had any issues with T1, but my thoughts are blurred by the issues on T2, so I'll need a reminder here @jialincheoh @sbrunswi

**Comment by harshpavuluri** [comment]
Since T2 is now fixed with screenshots, images, and the recording, closing here
