### ISSUE TITLE
Fixes to tutorial #3 and #4

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/Tutorials-COVID-19#29]
Issues identified in tutorial sesssion

- [x] link to schema is outdated in tutorial 3
- [x] Link to bigquery SQL syntax
- [x] Additional commands on how to list projects and tables that you have access to!

**Comment by harshpavuluri** [comment]
Link to hack data:
https://docs.google.com/spreadsheets/d/e/2PACX-1vTw11QCzmLmg1RHtwd3Xs4FpFP3zzZEr7-BKJ-hceqxYInKVsMyBkD20BySWDA1sr2p4yhpwsyY8SLl/pubhtml

Link to Tutorial data:
https://docs.google.com/spreadsheets/d/e/2PACX-1vRL-897BXh4BQFYMX4B06knO40emWSWC4Bug12QhXSE-wYZcqZZwLDPaLHb3AfOO0wEMSyKKTZaqtDn/pubhtml

**Comment by harshpavuluri** [comment]
Links have been updated T3 for the schema. Permissions errors should be resolved now. T3 is updated on live and dev now
