### ISSUE TITLE
Tutorials for Spring-Summer 2021

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/Tutorials-COVID-19#5]
**Is your feature request related to a problem? Please describe**
The tutorial material needs to be finalized for Spring 2021 - Tutorial #3 and #4 and #5 in particular - Most of it is done but #3 needs some rework. Also, all markdown files need to be reviewed again for broken links. 

**Describe the solution you'd like**
Clear, well-written tutorials that are meeting the expectations of an "intermediate" programmer! Currently, tutorials #2 and #3 really could be improved.

Describe alternatives you've considered
NA

Additional context
I think the R tutorial for #2 gives some good guidance on the depth of the notebook.

**Comment by harshpavuluri** [comment]
- [x] MD check for Tutorial 1
- [ ] MD check for Tutorial 2 (Need to update the schema link)
- [ ] MD check for Tutorial 3 (Update BigQuery link, bug here)
- [x] MD check for Tutorial 4
