### ISSUE TITLE
Create two additionl tutorial markdowns #6 and #7 - called general infomaterial Python programming and general info material ML

### ISSUE THREAD

**Issue by ybvau** [ironhacks/Tutorials-COVID-19#7]
**Problem**
We need general "onboarding" material that points to existing courses, intros related to Python, and maybe ML in general.
Since we do not have any statistics/ML tutorials such an info material is important.

**Solution**: Add a new markdown here in the tutorial Spring and call it External_tutorials.md with links to curated tutorials and trainings. 

Here is some input into this: 

Programming in Python

1. Python programming tutorial by Freecodecamp - https://www.youtube.com/watch?v=rfscVS0vtbw
2. Python programming tutorial by Udacity - https://www.udacity.com/course/introduction-to-python–ud1110
3. Additional python programming tutorial - https://www.youtube.com/watch?v=N4mEzFDjqtA
4. Programming for Data Science with Python - https://www.udacity.com/course/programming-for-data-science-nanodegree–nd104
5. Introduction to Data Visualization in Python - https://towardsdatascience.com/introduction-to-data-visualization-in-python-89a54c97fbed

We could call one 
**Basic intro into Python**
**For Beginners - How to get started with ML**

**Comment by harshpavuluri** [comment]
Link I used for August hack:
https://www.datacamp.com/community/tutorials/moving-averages-in-pandas

My notebook in a public personal repo:
https://github.com/harshpavuluri/ironhackchallenge1/blob/master/submission_prediction_output.ipynb

**Comment by sbrunswi** [comment]
@harshpavuluri  - please do not publish your submission in your repo publically unless you remove identifiers that connect it to the particular challenge!

**Comment by harshpavuluri** [comment]
Links for beginning predictive modeling:

1. https://towardsdatascience.com/end-to-end-python-framework-for-predictive-modeling-b8052bb96a78
2. https://medium.datadriveninvestor.com/a-simple-guide-to-creating-predictive-models-in-python-part-1-8e3ddc3d7008
3. https://microsoft.github.io/sql-ml-tutorials/python/rentalprediction/step/2.html
4. https://www.analyticsvidhya.com/blog/2015/09/build-predictive-model-10-minutes-python/
5. https://machinelearningmastery.com/machine-learning-in-python-step-by-step/

**Comment by ybvau** [comment]
1. Coursera Predictive Analytics class (IBM) https://www.coursera.org/learn/data-analysis-with-python
2. Freecodecamp Data Analysis with Python https://www.freecodecamp.org/news/learn-data-analysis-with-python-course/
3. Coursera Fitting Statistical Models to Data (UMich) https://www.coursera.org/lecture/fitting-statistical-models-data-python/welcome-to-the-course-YWegA
4. Statistical Analysis and Modeling with Python https://towardsdatascience.com/an-introduction-to-statistical-analysis-and-modelling-with-python-ef816b67f8ff
5. Building a Prediction Model Step by Step Python https://towardsdatascience.com/step-by-step-guide-building-a-prediction-model-in-python-ac441e8b9e8b

**Comment by ybvau** [comment]
#6:  5f23660
#7:  0c85e1a

**Comment by harshpavuluri** [comment]
These look pretty good to me....Probably maybe some hyperlink magic to condense those long links and I think we should be good

**Comment by harshpavuluri** [comment]
https://github.com/ironhacks/Tutorials-COVID-19/blob/master/tutorials-Spring-2021/python/python-infomaterial.md
https://github.com/ironhacks/Tutorials-COVID-19/blob/master/tutorials-Spring-2021/python/ml-infomaterial.md

Cleaner links finished

**Comment by ERThompson765** [comment]
@ybvau @sbrunswi Thanks Bryan for creating the md files and @harshpavuluri for helping with links. These are now published in the tutorials section of hack
